# FEATURE ENGINEERING(SCALING) 

- StandardScaler
- MinMaxScaler
- MaxAbsScaler
- RobustScaler

In [77]:
## importing required libraries
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
boston_data = load_boston()

In [6]:
## creating Dataset from load_boston
df = pd.DataFrame(boston_data.data,columns=boston_data.feature_names)

In [14]:
# creating medv feature using load_boston.target
df[' medv'] = boston_data.target

In [15]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT   medv  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [16]:
## cheacking datatypes of the each and every column
df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
 medv      float64
dtype: object

In [17]:
## description of the data
df.describe().T

count        mean         std        min         25%        50%  \
CRIM     506.0    3.613524    8.601545    0.00632    0.082045    0.25651   
ZN       506.0   11.363636   23.322453    0.00000    0.000000    0.00000   
INDUS    506.0   11.136779    6.860353    0.46000    5.190000    9.69000   
CHAS     506.0    0.069170    0.253994    0.00000    0.000000    0.00000   
NOX      506.0    0.554695    0.115878    0.38500    0.449000    0.53800   
RM       506.0    6.284634    0.702617    3.56100    5.885500    6.20850   
AGE      506.0   68.574901   28.148861    2.90000   45.025000   77.50000   
DIS      506.0    3.795043    2.105710    1.12960    2.100175    3.20745   
RAD      506.0    9.549407    8.707259    1.00000    4.000000    5.00000   
TAX      506.0  408.237154  168.537116  187.00000  279.000000  330.00000   
PTRATIO  506.0   18.455534    2.164946   12.60000   17.400000   19.05000   
B        506.0  356.674032   91.294864    0.32000  375.377500  391.44000   
LSTAT    506.0   12.653063    7.141062    1.73000    6.950000   11.36000   
 medv    506.0   22.532806    9.197104    5.00000   17.025000   21.20000   

                75%       max  
CRIM       3.677083   88.9762  
ZN        12.500000  100.0000  
INDUS     18.100000   27.7400  
CHAS       0.000000    1.0000  
NOX        0.624000    0.8710  
RM         6.623500    8.7800  
AGE       94.075000  100.0000  
DIS        5.188425   12.1265  
RAD       24.000000   24.0000  
TAX      666.000000  711.0000  
PTRATIO   20.200000   22.0000  
B        396.225000  396.9000  
LSTAT     16.955000   37.9700  
 medv     25.000000   50.0000

- independent features and dependent features

In [18]:
## seperating Independent columns
X = df.iloc[:,:-1]

In [20]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [21]:
## seperating target column
y = df.iloc[:,-1]

In [22]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name:  medv, Length: 506, dtype: float64

In [45]:
## splittign the data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [25]:
## importing StandardScaler
from sklearn.preprocessing import StandardScaler

In [26]:
## creating Object for StandardScaler model
scaler = StandardScaler()

In [27]:
#fitting the data
scaler.fit(X_train)

StandardScaler()

In [28]:
# transforming the data 
X_train_tf = scaler.transform(X_train)

In [29]:
X_test_tf = scaler.transform(X_test)

In [32]:
X_train_tf[:2]

array([[-0.41425879, -0.50512499, -1.29214218, -0.28154625, -0.85108479,
         0.14526384, -0.365584  ,  1.08162833, -0.74617905, -1.11279004,
         0.18727079,  0.39651419, -1.01531611],
       [-0.40200818, -0.50512499, -0.16208345, -0.28154625, -0.08796708,
        -0.20840082,  0.13394078, -0.48787608, -0.39846419,  0.15008778,
        -0.21208981,  0.3870674 , -0.05366252]])

In [35]:
X_test_tf[:2]

array([[-0.406801  , -0.50512499, -1.02225586, -0.28154625, -0.40521827,
         0.12577051,  0.55383118, -0.52734802, -0.51436915, -0.66777595,
        -0.74457062,  0.41241246, -0.47605794],
       [-0.41105674,  1.26662874, -0.68165068,  3.55181427, -0.94540271,
         0.60196466, -1.29947815,  0.14683092, -0.6302741 , -0.92035152,
        -0.30083661,  0.42854113, -1.25185755]])

In [37]:
## printing mean of each column
print("mean of each column:",scaler.mean_)

mean of each column: [3.46988686e+00 1.14039548e+01 1.11330508e+01 7.34463277e-02
 5.57259322e-01 6.32567232e+00 6.87997175e+01 3.76587401e+00
 9.43785311e+00 4.07042373e+02 1.82779661e+01 3.59701808e+02
 1.24211299e+01]


In [38]:
## printing Stadard Deviation of each column
print("Stadard Deviation of each column:",scaler.scale_)

Stadard Deviation of each column: [8.30407703e+00 2.25765011e+01 6.92884344e+00 2.60867715e-01
 1.16626831e-01 7.18194456e-01 2.76262572e+01 2.12302684e+00
 8.62775916e+00 1.66286870e+02 2.25360235e+00 8.68019175e+01
 7.10234960e+00]


## MinMaxScaler 

-  MinMaxScaler squeezes the values of the variables between 0 and 1

In [46]:
## importing MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

In [47]:
MMS = MinMaxScaler()

In [48]:
MMS.fit(X_train)

MinMaxScaler()

In [49]:
X_train_mms = MMS.transform(X_train)

In [50]:
X_test_mms

array([[9.29781490e-04, 0.00000000e+00, 1.07048624e-01, ...,
        4.25531915e-01, 9.96469817e-01, 2.01710817e-01],
       [5.32556177e-04, 4.21052632e-01, 1.96004523e-01, ...,
        5.31914894e-01, 1.00000000e+00, 4.96688742e-02],
       [1.08669336e-03, 0.00000000e+00, 1.00000000e+00, ...,
        7.97872340e-01, 9.82878612e-01, 4.50883002e-01],
       ...,
       [5.82091320e-03, 0.00000000e+00, 1.88088956e-01, ...,
        5.10638298e-01, 9.62428766e-01, 8.00220751e-02],
       [6.26299778e-02, 0.00000000e+00, 6.36637769e-01, ...,
        8.08510638e-01, 2.51828131e-01, 3.99834437e-01],
       [1.11454521e-01, 0.00000000e+00, 6.36637769e-01, ...,
        8.08510638e-01, 9.78869333e-01, 4.05905077e-01]])

In [51]:
X_test_mms = MMS.transform(X_test)

In [52]:
X_test_mms

array([[9.29781490e-04, 0.00000000e+00, 1.07048624e-01, ...,
        4.25531915e-01, 9.96469817e-01, 2.01710817e-01],
       [5.32556177e-04, 4.21052632e-01, 1.96004523e-01, ...,
        5.31914894e-01, 1.00000000e+00, 4.96688742e-02],
       [1.08669336e-03, 0.00000000e+00, 1.00000000e+00, ...,
        7.97872340e-01, 9.82878612e-01, 4.50883002e-01],
       ...,
       [5.82091320e-03, 0.00000000e+00, 1.88088956e-01, ...,
        5.10638298e-01, 9.62428766e-01, 8.00220751e-02],
       [6.26299778e-02, 0.00000000e+00, 6.36637769e-01, ...,
        8.08510638e-01, 2.51828131e-01, 3.99834437e-01],
       [1.11454521e-01, 0.00000000e+00, 6.36637769e-01, ...,
        8.08510638e-01, 9.78869333e-01, 4.05905077e-01]])

In [78]:
## printing Min value of each column
print("Min value of each column:",MMS.data_min_)

Min value of each column: [9.0600e-03 0.0000e+00 1.2100e+00 0.0000e+00 3.8500e-01 3.8630e+00
 2.9000e+00 1.1296e+00 1.0000e+00 1.8700e+02 1.2600e+01 3.2000e-01
 1.7300e+00]


In [79]:
## printing max value of each column
print("max value of each column:",MMS.data_max_)

max value of each column: [ 88.9762  95.      27.74     1.       0.871    8.78   100.      12.1265
  24.     711.      22.     396.9     37.97  ]


In [56]:
MMS.data_range_

array([8.896714e+01, 9.500000e+01, 2.653000e+01, 1.000000e+00,
       4.860000e-01, 4.917000e+00, 9.710000e+01, 1.099690e+01,
       2.300000e+01, 5.240000e+02, 9.400000e+00, 3.965800e+02,
       3.624000e+01])

## MaxAbs Scaler

- Maximum absolute scaling scales the data to its maximum value; that is, it divides every observation by the maximum value of the variable.The values are vary approximately within the range of -1 to 1

In [57]:
## importing MaxAbsScaler
from sklearn.preprocessing import MaxAbsScaler

In [58]:
MAS = MaxAbsScaler()

In [59]:
MAS.fit(X_train)

MaxAbsScaler()

In [60]:
X_train_mas = MAS.transform(X_train)

In [61]:
X_train_mas

array([[3.35482972e-04, 0.00000000e+00, 7.85868782e-02, ...,
        8.50000000e-01, 9.92995717e-01, 1.37213590e-01],
       [1.47882243e-03, 0.00000000e+00, 3.60850757e-01, ...,
        8.09090909e-01, 9.90929705e-01, 3.17092441e-01],
       [1.92658261e-03, 0.00000000e+00, 2.49098774e-01, ...,
        8.13636364e-01, 1.00000000e+00, 2.68896497e-01],
       ...,
       [1.68696798e-04, 8.42105263e-01, 7.24585436e-02, ...,
        7.72727273e-01, 9.84983623e-01, 1.57756123e-01],
       [1.25431295e-01, 0.00000000e+00, 6.52487383e-01, ...,
        9.18181818e-01, 2.76769967e-01, 6.12852252e-01],
       [2.57102461e-03, 0.00000000e+00, 3.08579668e-01, ...,
        9.50000000e-01, 1.78382464e-01, 2.79957861e-01]])

In [62]:
X_test_mas = MAS.transform(X_test)

In [63]:
X_test_mas

array([[1.03151180e-03, 0.00000000e+00, 1.45998558e-01, ...,
        7.54545455e-01, 9.96472663e-01, 2.38082697e-01],
       [6.34326932e-04, 4.21052632e-01, 2.31074261e-01, ...,
        8.00000000e-01, 1.00000000e+00, 9.29681327e-02],
       [1.18840769e-03, 0.00000000e+00, 1.00000000e+00, ...,
        9.13636364e-01, 9.82892416e-01, 4.75902028e-01],
       ...,
       [5.92214547e-03, 0.00000000e+00, 2.23503965e-01, ...,
        7.90909091e-01, 9.62459058e-01, 1.21938372e-01],
       [6.27254255e-02, 0.00000000e+00, 6.52487383e-01, ...,
        9.18181818e-01, 2.52431343e-01, 4.27179352e-01],
       [1.11544997e-01, 0.00000000e+00, 6.52487383e-01, ...,
        9.18181818e-01, 9.78886369e-01, 4.32973400e-01]])

In [67]:
print("Max values:",MAS.max_abs_)

Max values: [ 88.9762  95.      27.74     1.       0.871    8.78   100.      12.1265
  24.     711.      22.     396.9     37.97  ]


## Robust Scaling 

- robust scaling produces more robust estimates for the center and value range of the variable, and is recommended if the data contains outliers.

In [68]:
from sklearn.preprocessing import RobustScaler

In [69]:
RS = RobustScaler()

In [70]:
RS.fit(X_train)

RobustScaler()

In [71]:
X_train_rs = RS.transform(X_train)

In [72]:
X_train_rs

array([[-7.08452530e-02,  0.00000000e+00, -5.79028527e-01, ...,
         2.81690141e-02,  1.29963899e-01, -6.10413885e-01],
       [-3.90483431e-02,  0.00000000e+00,  2.46723207e-02, ...,
        -2.25352113e-01,  8.76740588e-02,  1.19092123e-01],
       [-2.65958818e-02,  0.00000000e+00, -2.14340786e-01, ...,
        -1.97183099e-01,  2.73336772e-01, -7.63684913e-02],
       ...,
       [-7.54836698e-02,  4.00000000e+00, -5.92135698e-01, ...,
        -4.50704225e-01, -3.40381640e-02, -5.27102804e-01],
       [ 3.40813927e+00,  0.00000000e+00,  6.48419429e-01, ...,
         4.50704225e-01, -1.45306859e+01,  1.31855808e+00],
       [-8.67358939e-03,  0.00000000e+00, -8.71241326e-02, ...,
         6.47887324e-01, -1.65446106e+01, -3.15086782e-02]])

In [73]:
X_test_rs = RS.transform(X_test)

In [74]:
X_test_rs

array([[ -0.0514883 ,   0.        ,  -0.43484965, ...,  -0.56338028,
          0.20113461,  -0.20133511],
       [ -0.06253424,   2.        ,  -0.25289129, ...,  -0.28169014,
          0.27333677,  -0.78985314],
       [ -0.04712494,   0.        ,   1.39167309, ...,   0.42253521,
         -0.07684373,   0.76315087],
       ...,
       [  0.08452296,   0.        ,  -0.2690825 , ...,  -0.33802817,
         -0.49510057,  -0.67236315],
       [  1.66425395,   0.        ,   0.64841943, ...,   0.45070423,
        -15.02888087,   0.56555407],
       [  3.02195356,   0.        ,   0.64841943, ...,   0.45070423,
         -0.15884477,   0.58905207]])

In [75]:
## printing Medians of each column
print("Medians of each Column:",RS.center_)

Medians of each Column: [2.5651e-01 0.0000e+00 9.6900e+00 0.0000e+00 5.3800e-01 6.2275e+00
 7.7350e+01 3.1073e+00 5.0000e+00 3.3000e+02 1.8600e+01 3.9160e+02
 1.0925e+01]


In [80]:
## printing IQR values
print("IQR stored in RobustScaler:",RS.scale_)

IQR stored in RobustScaler: [3.1993675e+00 2.0000000e+01 1.2970000e+01 1.0000000e+00 1.8100000e-01
 7.9225000e-01 4.7450000e+01 3.3270000e+00 2.0000000e+01 3.8700000e+02
 3.5500000e+00 1.9390000e+01 9.3625000e+00]
